FROM balenalib/jetson-xavier-debian:latest

RUN [ cross-build-start ]
RUN apt-get update && apt-get install -y python3-setuptools python3-pip
RUN pip3 install tornado
COPY ./ /opt/farm-ng/src/tractor
RUN [ cross-build-end ]
CMD ["/opt/farm-ng/src/tractor/env.sh", "python3", "-m", "farm_ng.tractor.frontend", "--rtkrover-host=rtkrover"]
