FROM golang:alpine
# redo
# Install protoc
RUN apk add --update-cache \
  git \
  nodejs-current-npm \
  protobuf \
  protobuf-dev

# Install protoc plugins
RUN go get -u github.com/isherman/protoc-gen-twirp_tornado_srv
RUN npm install -g long ts-proto
