FROM python:3-slim

COPY bootstrap-apt.sh ./
COPY requirements*.txt ./
COPY third_party/protoc-gen-validate/requirements.txt third_party/protoc-gen-validate/requirements.txt
RUN ./bootstrap-apt.sh
COPY bootstrap-venv.sh ./
RUN ./bootstrap-venv.sh

# env/ is wiped out by mounting the dictory... Needs fixing.
CMD ["./env.sh", "python", "-m", "farm_ng.pose_vis_toy"]
