FROM python:3-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  git \
  make

COPY requirements*.txt ./
COPY third_party/protoc-gen-validate/requirements.txt third_party/protoc-gen-validate/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

CMD ["./env.sh", "python3", "-m", "farm_ng.tractor.sim"]
